authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

import mainapp.views as mainapp

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
    re_path(r'^callback/', include('callbackapp.urls', namespace='callback')),
    re_path(r'^news/', include('newsapp.urls', namespace='news')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    re_path(r'^', include('social_django.urls', namespace='social')),
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
# import mainapp.views as mainapp
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),

    re_path(r'^shop/$', mainapp.shop, name='shop'),
    re_path(r'^shop/page/(?P<page>\d+)/$', mainapp.shop, name='shop_paginator'),

    re_path(r'^product/(?P<slug>[-\w]+)/$', mainapp.product, name='product'),

    re_path(r'^category/(?P<slug>[-\w]+)/$', mainapp.category, name='category'),
    re_path(r'^category/(?P<slug>[-\w]+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    re_path(r'^search/$', mainapp.search, name='search'),
    # re_path(r'^search/$', mainapp.SearchView.as_view(), name='search'),

]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name="ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя категории', max_length=128, unique=True)
    slug = models.SlugField(verbose_name='Слаг', max_length=128, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='Активность', default=True)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'


# class ProductSubCategory(models.Model):
#     category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
#     name = models.CharField(verbose_name='Имя подкатегории', max_length=128, unique=True)
#     description = models.TextField(verbose_name='Описание подкатегории', blank=True)
#
#     def __str__(self):
#         return f"{self.name}"
#
#     class Meta:
#         verbose_name = 'Подкатегория товара'
#         verbose_name_plural = 'Подкатегории товаров'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    # subcategory = models.ForeignKey(ProductSubCategory, on_delete=models.CASCADE, default=None)
    name = models.CharField(verbose_name='Название товара', max_length=128, unique=True)
    slug = models.SlugField(verbose_name='слаг', max_length=128, unique=True)
    image = models.ImageField(upload_to='product_images', default='users_avatars/default.jpg')
    short_desc = models.TextField(verbose_name='Краткое описание товара', blank=True)
    description = models.TextField(verbose_name='Полное описание товара', blank=True)
    price = models.DecimalField(verbose_name='Цена товара', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='На складе', default=0)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    is_active = models.BooleanField(verbose_name='Активность', default=True)
    to_order = models.BooleanField(verbose_name='Под заказ', default=False)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

mainapp/views.py
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from newsapp.models import News
from .models import *
from django.shortcuts import render_to_response


def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        founded_products = Product.objects.filter(
            Q(name__icontains=q) | Q(description__icontains=q) | Q(short_desc__icontains=q)
        ).order_by('name')
        # founded_products = Product.objects.filter(
        #     Q(name__in=q) | Q(description__in=q) | Q(short_desc__in=q)
        # ).order_by('name')
        context = {
            'page_title': 'Результаты поиска',
            'founded_products': founded_products,
            'query': q,
        }
        return render_to_response('mainapp/search.html', context)
    else:
        context = {
            'page_title': 'Результаты поиска',
        }
        return render_to_response('mainapp/search.html', context)


# def search_form(request):
#     return render_to_response('mainapp/search.html')


# class SearchView(View):
#     template_name = "mainapp/search.html"
#
#     def get_result_search(self, request, *args, **kwargs):
#         query = self.request.GET.get('q')
#         founded_products = Product.objects.filter(Q(name__icontains=query))
#         context = {
#             'founded_products': founded_products,
#             'query': query,
#         }
#         return render(self.request, self.template_name, context)


# def get_products_menu():
#     return ProductCategory.objects.all().exclude(is_active=False)

# def bad_search(request):
#     # The following line will raise KeyError if 'q' hasn't
#     # been submitted!
#     message = 'You searched for: %r' % request.GET['q']
#     return HttpResponse(message)


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')
    else:
        []


def index(request):
    all_products = Product.objects.all().order_by('?')[:6]
    all_news = News.objects.all().order_by('-created')[:4]
    context = {
        'page_title': 'РФснаб.ру - комплексное снабжение',
        'all_products': all_products,
        'all_news': all_news,
        # 'basket': get_basket(request),
    }
    return render(request, 'mainapp/index.html', context)


def shop(request, slug=None, page=1):
    all_products = Product.objects.all()
    paginator = Paginator(all_products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    context = {
        'page_title': 'каталог',
        'all_products': products_paginator,
    }
    return render(request, 'mainapp/shop.html', context)


def category(request, slug, page=1):
    all_products = Product.objects.filter(category__slug=slug).exclude(is_active=False)
    single_category = ProductCategory.objects.filter(slug=slug)
    paginator = Paginator(all_products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    context = {
        'all_products': products_paginator,
        'single_category': single_category,
    }
    return render(request, "mainapp/category.html", context)


def product(request, slug):
    single_product = Product.objects.filter(slug=slug)
    same_products = Product.objects.all().filter(category__product__slug=slug).exclude(slug=slug).order_by('?')[:4]
    context = {
        'single_product': single_product,
        'same_products': same_products,
    }
    return render(request, "mainapp/product.html", context)

mainapp/templates/mainapp/includes/inc__breadcrumbs.html
<div class="breadcrumbs">
    <a href="/">РФснаб.ру</a> /
    <a href="{% url 'main:shop' %}">Каталог</a>
    {% for item in single_category %}/ {{ item.name }}{% endfor %}
    {% for item in single_product %}/
        <a href="{% url 'main:category' item.category.slug %}">
        {{ item.category.name }}
        </a>
    {% endfor %}
    {% for item in single_product %}/ {{ item.name }}{% endfor %}
</div>

mainapp/templates/mainapp/includes/inc__menu_wrapper.html
<div class="menu-wrapper">
    <ul class="left-menu">
        <li><a href="{% url 'main:index' %}" class="menu-link-left">Главная</a></li>
        <li><a href="#" class="menu-link-left">О компании</a></li>
        <li><a href="{% url 'main:shop' %}" class="menu-link-left">Каталог</a></li>
        <li><a href="#" class="menu-link-left">Доставка</a></li>
        <li><a href="{% url 'news:index' %}" class="menu-link-left">Новости</a></li>

    </ul>
    <ul class="right-menu">
    {% if user.is_authenticated %}
        <li>
        <p class="welcome_text">Доброго времени суток, </p>
        </li>
        <li>
            <div class="dropdown">
  <button class="btn btn-dropdown-link dropdown-toggle" type="button"
          id="dropdownMenuButton" data-toggle="dropdown">
    <p class="welcome_text">{{ user.first_name|default:'Пользователь' }} </p>

  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a href="{% url 'auth:update' %}" class="dropdown-item">
                    Профиль
                </a>
    <a class="dropdown-item" href="{% url 'order:orders_list' %}">Заказы</a>

  </div>
</div>
    </li>
     {% endif %}

{#    <li>#}
{#        <p class="welcome_text">Доброго времени суток, </p>#}
{#        </li>#}
{#        <li>#}
{#    <div class="dropdown">#}
{#  <button class="btn btn-dropdown-link dropdown-toggle" type="button"#}
{#          id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#    <p class="welcome_text">{{ user.first_name|default:'Пользователь' }} </p>#}
{##}
{#  </button>#}
{#  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">#}
{#    <a href="{% url 'auth:update' %}" class="dropdown-item">#}
{#                    Профиль#}
{#                </a>#}
{#    <a class="dropdown-item" href="{% url 'order:orders_list' %}">Заказы</a>#}
{##}
{#  </div>#}
{#</div>#}
{#    </li>#}





{#        <li>#}
{#            {% if user.is_authenticated %}#}
{#                <p class="welcome_text">Доброго времени суток, </p>#}
{#                <a href="{% url 'auth:update' %}" class="update_link">#}
{#                    {{ user.first_name|default:'Пользователь' }}#}
{#                </a>#}
{#            {% endif %}#}
{#        </li>#}
        <li>
            {% if user.is_superuser %}
                <a href="{% url 'myadmin:index' %}" class="menu-link-right">
                    Админка
                </a>
            {% endif %}
        </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}" class="menu-link-right">Выход</a>
            {% else %}
                <a href="{% url 'auth:login' %}" class="menu-link-right">Личный кабинет</a>
            {% endif %}
        </li>
        {#        <li><a href="#" class="menu-link-right">Личный кабинет </a></li>#}
        <li><a href="{% url 'basket:index' %}" class="menu-link-right">Корзина</a></li>
    </ul>
</div>

mainapp/templates/mainapp/includes/inc__sort_category_left_col.html
{% load static %}

<ul class="sort-category-left-col">
    {% for item in products_menu %}
        <li class="row-sort-category-left-col">
        <a href="{% url 'main:category' item.slug %}" class="link-sort-category-left-col">
            {{ item.name }}
        </a>
    {% endfor %}
{#    <ul class="sort-subcategory-left-col">#}
{#        #}
{#        <li class="row-sort-subcategory-left-col">#}
{##}
{#            <a href="#" class="link-sort-subcategory-left-col">#}
{#                Огнетушители#}
{#            </a>#}
{##}
{#        </li>#}
{##}
{#        <li class="row-sort-subcategory-left-col">#}
{#            <a href="#" class="link-sort-subcategory-left-col">#}
{#                Рукава, стволы, запорная арматура#}
{#            </a>#}
{#        </li>#}
{#        <li class="row-sort-subcategory-left-col">#}
{#            <a href="#" class="link-sort-subcategory-left-col">#}
{#                Шкафы, щиты, подставки, инвентарь#}
{#            </a>#}
{#        </li>#}
{#    </ul>#}
{#    </li>#}
{#    <li class="row-sort-category-left-col"><a href="#" class="link-sort-category-left-col">Продукция#}
{#        торговой марки Шанс</a></li>#}
{#    <li class="row-sort-category-left-col"><a href="#" class="link-sort-category-left-col">Средства#}
{#        индивидуальной защиты</a></li>#}
</ul>

mainapp/templates/mainapp/includes/inc__wrapper_add_cart.html
{% if basket %}
    <div class="wrapper_add_cart">
        <p class="wrapper_add_cart_text">Итого в корзине товаров:
            <b>{{ basket.0.total_quantity }}</b>
            на сумму <b>{{ basket.0.total_cost|floatformat:2 }}</b> руб.
        </p>
    </div>
{% else %}
    <div class="wrapper_add_cart">
        <p class="wrapper_add_cart_text">Итого в корзине товаров:
            <b>0</b> на сумму <b>0</b> руб.
        </p>
    </div>
{% endif %}