authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

import mainapp.views as mainapp

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
    re_path(r'^callback/', include('callbackapp.urls', namespace='callback')),
    re_path(r'^news/', include('newsapp.urls', namespace='news')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    re_path(r'^', include('social_django.urls', namespace='social')),
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
# import mainapp.views as mainapp
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),

    re_path(r'^shop/$', mainapp.shop, name='shop'),
    re_path(r'^shop/page/(?P<page>\d+)/$', mainapp.shop, name='shop_paginator'),

    re_path(r'^product/(?P<slug>[-\w]+)/$', mainapp.product, name='product'),

    re_path(r'^category/(?P<slug>[-\w]+)/$', mainapp.category, name='category'),
    re_path(r'^category/(?P<slug>[-\w]+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    re_path(r'^search/$', mainapp.search, name='search'),
    # re_path(r'^search/$', mainapp.SearchView.as_view(), name='search'),

]

authapp/models.py
from datetime import timedelta
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class ShopUser(AbstractUser):
    avatar = models.ImageField(verbose_name='аватар',
                               upload_to='users_avatars',
                               blank=True,
                               default='users_avatars/default_avatar.png')
    age = models.PositiveIntegerField(verbose_name='возраст', default=18)
    activation_key = models.CharField(verbose_name='ключ подтверждения',
                                      max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(verbose_name='актуальность ключа',
                                                  default=(now() + timedelta(hours=48)))

    def is_activation_key_expired(self):
        if now() <= self.activation_key_expires:
            return False
        else:
            return True


class ShopUserProfile(models.Model):
    MALE = 'М'
    FEMALE = 'Ж'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
    )

    user = models.OneToOneField(ShopUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    tagline = models.CharField(verbose_name='теги', max_length=128, blank=True)
    about_me = models.TextField(verbose_name='о себе', max_length=512, blank=True)
    gender = models.CharField(verbose_name='пол', max_length=1, choices=GENDER_CHOICES, blank=True)
    country = models.CharField(verbose_name='страна', max_length=38, blank=True)
    city = models.CharField(verbose_name='город', max_length=38, blank=True)
    language = models.CharField(verbose_name='язык', max_length=38, blank=True)

    @receiver(post_save, sender=ShopUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            ShopUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=ShopUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.shopuserprofile.save()

authapp/forms.py
import hashlib
import random
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms import forms, HiddenInput
from django import forms
from authapp.models import ShopUser, ShopUserProfile


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Лицам моложе 18-ти лет запрещено регистрироваться на сайте!")
        return data

    def clean_avatar(self):
        data = self.cleaned_data['avatar']
        if len(data) > (300 * 1024):
            raise forms.ValidationError("Размер аватарки не может превышать 300К")
        return data

    def save(self):
        user = super(ShopUserRegisterForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()
        return user


class ShopUserUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Лицам моложе 18-ти лет запрещено регистрироваться на сайте!")
        return data


class ShopUserProfileEditForm(forms.ModelForm):
    # aboutMe = forms.CharField(label='О себе123', widget=forms.Textarea)

    class Meta:
        model = ShopUserProfile
        exclude = ('user',)



    def __init__(self, *args, **kwargs):
        super(ShopUserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'
        self.fields['about_me'].widget.attrs.update({'class': 'about_me_textarea'})

authapp/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from authapp.forms import *
from django.contrib import auth
from django.conf import settings
from django.db import transaction


def login(request):
    next = request.GET['next'] if 'next' in request.GET.keys() else None
    if request.method == 'POST':
        form = ShopUserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                next = request.POST['next'] if 'next' in request.POST.keys() else None
                # print(f'next: {next}')
                auth.login(request, user)
                return HttpResponseRedirect(reverse('mainapp:index') if not next else next)
    else:
        form = ShopUserLoginForm()

    context = {
        'page_title': 'личный кабинет',
        'form': form,
        'next': next,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('mainapp:index'))


def register(request):
    if request.method == 'POST':
        form = ShopUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            if send_verify_mail(user):
                # print(f'Сообщение для подтверждения регистрации отправлено')
                return HttpResponseRedirect(reverse('authapp:login'))
            else:
                # print(f'Ошибка отправки сообщение для подтверждения регистрации')
                return HttpResponseRedirect(reverse('authapp:login'))
    else:
        form = ShopUserRegisterForm()
    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)


@transaction.atomic
def update(request):
    if request.method == 'POST':
        edit_form = ShopUserUpdateForm(request.POST, request.FILES, instance=request.user)
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:update'))
    else:
        edit_form = ShopUserUpdateForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.shopuserprofile)

    context = {
        'page_title': 'редактирование профиля',
        'edit_form': edit_form,
        'profile_form': profile_form,
    }
    return render(request, 'authapp/update.html', context)


def send_verify_mail(user):
    verify_link = reverse(
        'auth:verify',
        args=[user.email, user.activation_key])
    title = 'Подтверждение учетной записи {}'.format(user.username)
    message = 'Для подтверждения учетной записи {} на портале перейдите по ссылке: {}{}'.format(user.username, settings.DOMAIN_NAME, verify_link)
    print = 'from: {}, to: {}'.format(settings.EMAIL_HOST_USER, user.email)
    return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


def verify(request, email, activation_key):
    try:
        user = ShopUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            print('user {} is activated'.format(user))
            user.is_active = True
            user.save()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            context = {
                'page_title': 'подтверждение регистрации',
            }
            return render(request, 'authapp/verification.html', context)
        else:
            print('error activation user: {}'.format(user))
            context = {
                'page_title': 'подтверждение регистрации',
            }
            return render(request, 'authapp/verification.html', context)
    except Exception as e:
        print('error activation user: {}'.format(e.args))
    return HttpResponseRedirect(reverse('main:index'))

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content-container %}

    <div class="content-container">

        <div class="form_wrapper">
            <h1 class="regisration_title_lk">Личный кабинет</h1>
            <div class="social_icon_box">
                        <p class="social_title">Войти с помощью:</p>
<a href="{% url 'social:begin' 'vk-oauth2' %}?next=/" class="auth_icon"></a></div>
            <form method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}">
                {% endif %}
                {{ form.as_p }}
                <input type="submit" value="войти" class="btn_auth">
            </form>
            <a href="{% url 'auth:register' %}" class="auth_register">Зарегистрироваться</a>

            {#        <a href="#" class="auth_title">Личный кабинет</a>#}
            {#        <div class="login_form">#}
            {#            <form action="">#}
            {#                <label class="field-label-registration">Логин</label>#}
            {##}
            {#                <input type="text" class="field_label_input" required=""/>#}
            {##}
            {#                <label class="field-label-registration">Пароль</label>#}
            {##}
            {#                <input type="password" class="field_label_input" required=""/>#}
            {##}
            {#                <button type="submit" class="btn_auth">Войти</button>#}
            {#            </form>#}
            {#        </div>#}
            {#    </div>#}
            {#    <div class="form_wrapper">#}
            {#        <a href="#" class="auth_title">Регистрация</a>#}
            {#        <div class="login_form">#}
            {#            <form action="">#}
            {#                <label class="field-label-registration">Email</label>#}
            {##}
            {#                <input type="email" class="field_label_input" required=""/>#}
            {##}
            {#                <button type="submit" class="btn_auth">Зарегистрироваться</button>#}
            {#            </form>#}
            {#        </div>#}
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content-container %}
    <div class="content-container">
        <div class="form_wrapper">
            <div class="login_form">
                <h1 class="regisration_title">Регистрация пользователя</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn_auth" value="зарегистрироваться">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/update.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content-container %}
    <div class="content-container">
        <div class="form_wrapper">
            <div class="login_form">
                <h1 class="regisration_title">Редактирование профиля пользователя</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ edit_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" class="btn_auth" value="сохранить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content-container %}
    <div class="content-container">
        <div class="form_wrapper">
            {% if user %}
                <h2 class="verification_title">Поздравляем!</h2>
                <br>
                <p>Пользователь {{ user.username }} подтвержден.</p>
            {% else %}
                <h4>Верификация не пройдена.</h4>
            {% endif %}
        <br>
        <a href="{% url 'main:shop' %}" class="btn_cart">
                    В каталог
                </a>
        </div>
    </div>
{% endblock %}