adminapp/urls.py
from django.urls import path, re_path
# import mainapp.views as mainapp
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # re_path(r'^$', adminapp.index, name='index'),
    re_path(r'^$', adminapp.ShopUserListView.as_view(), name='index'),

    re_path(r'^shopuser/create/$', adminapp.shopuser_create, name='shopuser_create'),
    re_path(r'^shopuser/update/(?P<pk>\d+)/$', adminapp.shopuser_update, name='shopuser_update'),
    re_path(r'^shopuser/delete/(?P<pk>\d+)/$', adminapp.shopuser_delete, name='shopuser_delete'),

    re_path(r'^productcategory/list/$', adminapp.productcategory_list, name='productcategory_list'),

    # re_path(r'^productcategory/create/$', adminapp.productcategory_create, name='productcategory_create'),
    re_path(r'^productcategory/create/$', adminapp.ProductCategoryCreateView.as_view(), name='productcategory_create'),

    # re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.productcategory_update, name='productcategory_update'),
    re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(),
            name='productcategory_update'),

    # re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.productcategory_delete, name='productcategory_delete'),
    re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='productcategory_delete'),

    re_path(r'^productcategory/products/(?P<pk>\d+)/$', adminapp.productcategory_products,
            name='productcategory_products'),

    re_path(r'^product/create/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path(r'^product/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),

    # re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
]

authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

import mainapp.views as mainapp

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
    re_path(r'^callback/', include('callbackapp.urls', namespace='callback')),
    re_path(r'^news/', include('newsapp.urls', namespace='news')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    re_path(r'^', include('social_django.urls', namespace='social')),
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms import forms, HiddenInput, ModelForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminCreateForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Лицам моложе 18-ти лет запрещено регистрироваться на сайте!")
        return data

    def clean_avatar(self):
        data = self.cleaned_data['avatar']
        if len(data) > (300 * 1024):
            raise forms.ValidationError("Размер аватарки не может превышать 300К")
        return data


class ShopUserAdminUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name',
                  'password', 'email', 'age', 'avatar', 'is_superuser', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Лицам моложе 18-ти лет запрещено регистрироваться на сайте!")
        return data


class ProductCategoryAdminUpdateForm(ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'


class ProductAdminUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_fields'

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from adminapp.forms import ShopUserAdminCreateForm, ShopUserAdminUpdateForm, ProductCategoryAdminUpdateForm, \
    ProductAdminUpdateForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserListView(ListView):
    model = ShopUser
    # template_name = 'adminapp/index.html'
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'панель администратора'
        return context


# @user_passes_test(lambda x: x.is_superuser)
# def index(request):
#     object_list = ShopUser.objects.all()
#
#     context = {
#         'page_title': 'Панель администратора',
#         'object_list': object_list,
#     }
#     return render(request, 'adminapp/index.html', context)


@user_passes_test(lambda x: x.is_superuser)
def shopuser_create(request):
    if request.method == 'POST':
        form = ShopUserAdminCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:index'))
    else:
        form = ShopUserAdminCreateForm()
    context = {
        'page_title': 'Создание пользователя',
        'form': form,
    }
    return render(request, 'adminapp/shopuser_create.html', context)


@user_passes_test(lambda x: x.is_superuser)
def shopuser_update(request, pk):
    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        form = ShopUserAdminUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:index'))
    else:
        form = ShopUserAdminUpdateForm(instance=user)
    context = {
        'page_title': 'редактирование пользователя',
        'form': form,
    }
    return render(request, 'adminapp/shopuser_create.html', context)


@user_passes_test(lambda x: x.is_superuser)
def shopuser_delete(request, pk):
    # get_object_or_404(ShopUser, pk=pk).delete()
    # return HttpResponseRedirect(reverse('adminapp:index'))
    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('myadmin:index'))
    elif request.method == 'GET':
        context = {
            'page_title': 'удаление пользователя',
            'object': user,
        }
        return render(request, 'adminapp/shopuser_delete.html', context)


@user_passes_test(lambda x: x.is_superuser)
def productcategory_list(request):
    object_list = ProductCategory.objects.all()

    context = {
        'page_title': 'категории товаров',
        'object_list': object_list,
    }
    return render(request, 'adminapp/productcategory_list.html', context)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    success_url = reverse_lazy('myadmin:productcategory_list')
    # fields ='__all__'
    form_class = ProductCategoryAdminUpdateForm
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'создание категории'
        return context


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_create(request):
#     if request.method == 'POST':
#         form = ProductCategoryAdminUpdateForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     else:
#         form = ProductCategoryAdminUpdateForm()
#     context = {
#         'page_title': 'создание категории',
#         'form': form,
#     }
#     return render(request, 'adminapp/productcategory_create.html', context)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    success_url = reverse_lazy('myadmin:productcategory_list')
    form_class = ProductCategoryAdminUpdateForm
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'изменение категории'
        return context


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_update(request, pk):
#     productcategory = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         form = ProductCategoryAdminUpdateForm(request.POST, request.FILES, instance=productcategory)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     else:
#         form = ProductCategoryAdminUpdateForm(instance=productcategory)
#     context = {
#         'page_title': 'изменение категории',
#         'form': form,
#     }
#     return render(request, 'adminapp/productcategory_create.html', context)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('myadmin:productcategory_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'удаление категории'
        return context


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_delete(request, pk):
#     productcategory = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         productcategory.is_active = False
#         productcategory.save()
#         return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     elif request.method == 'GET':
#         context = {
#             'page_title': 'удаление категории',
#             'object': productcategory,
#         }
#         return render(request, 'adminapp/productcategory_delete.html', context)


@user_passes_test(lambda x: x.is_superuser)
def productcategory_products(request, pk):
    productcategory = get_object_or_404(ProductCategory, pk=pk)
    context = {
        'page_title': 'товары категории',
        'productcategory': productcategory,
        'object_list': productcategory.product_set.all(),
    }
    return render(request, 'adminapp/product_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_create(request, pk):
    productcategory = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:productcategory_products', kwargs={'pk':pk}))
    else:
        form = ProductAdminUpdateForm(initial={'category': productcategory})
    context = {
        'page_title': 'создание товара',
        'form': form,
    }
    return render(request, 'adminapp/product_create.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:productcategory_products',
                                                kwargs={'pk':product.category.pk}))
    else:
        form = ProductAdminUpdateForm(instance=product)
    context = {
        'page_title': 'редактирование товара',
        'form': form,
        'product': product,
    }
    return render(request, 'adminapp/product_update.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('myadmin:productcategory_products',
                                            kwargs={'pk': product.category.pk}))
    elif request.method == 'GET':
        context = {
            'page_title': 'удаление товара',
            'object': product,
        }
        return render(request, 'adminapp/product_delete.html', context)


class ProductDetailView(DetailView):
    model = Product

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'карточка товара'
        return context


# @user_passes_test(lambda x: x.is_superuser)
# def product_read(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     context = {
#         'page_title': 'карточка товара',
#         'object': product,
#     }
#     return render(request, 'adminapp/product_read.html', context)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ page_title | title }}</title>
    {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {#        <link href="img/burning-ico.png" rel="shortcut icon" type="image/x-icon">#}
        <link href="{% static 'img/burning-ico.png' %}" rel="shortcut icon" type="image/x-icon">
        {#        <link href="{% static 'images/webclip.png' %}" rel="apple-touch-icon">#}
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="site-wrapper">
    <div class="top">


        {% block content-container %}
        {% endblock %}
    </div>
    <div class="footer">
        <div class="footer-wrapper">

            <p class="copyright-text">&copy; 2019, ООО «МСВ»</p>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content-container %}
    <h2 class="registration_title__myadmin">Панель администратора</h2>
    {% include 'adminapp/includes/inc__myadmin-menu.html' %}
    <div class="user_list_wrapper">
        <div class="user_list first-row">
            <div class="div-col"></div>
            <div class="div-col">
                <a href="{% url 'myadmin:shopuser_create' %}" class="btn-admin-2">Новый пользовательdrddy</a>
            </div>
            <div class="div-col"></div>
            <div class="div-col"></div>
            <div class="div-col"></div>
            <div class="div-col"></div>
        </div>
        {% for item in object_list %}
            <div class="user_list {% if not item.is_active %}not_active{% endif %}">
                <div class="div-col"><img src="/media/{{ item.avatar|default:'users_avatars/default_avatar.png' }}"
                                          alt="" class="user_avatar"></div>
                <div class="div-col">
                    <p class="text-admin">
                        <strong>{% if item.is_superuser %}администратор{% else %}пользователь{% endif %}</strong>
                    </p>
                    <a href="{% url 'myadmin:shopuser_update' item.pk %}" class="btn-admin-1">Редактировать</a>
                    <a href="{% url 'myadmin:shopuser_delete' item.pk %}" class="btn-admin-2">Удалить</a>
                </div>
                <div class="div-col">
                    <p class="text-admin"><strong>ник:</strong></p>
                    <p class="text-admin">{{ item.username }}</p>
                    {% if item.first_name %}
                        <p class="text-admin">{{ item.first_name|title }}</p>
                        {% if item.last_name %}
                            <p class="text-admin">{{ item.last_name|title }}</p>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="div-col">
                    <p class="text-admin"><strong>возраст:</strong></p>
                    <p class="text-admin">{{ item.age }}</p>
                </div>
                <div class="div-col">
                    <p class="text-admin"><strong>e-mail:</strong></p>
                    <p class="text-admin">{{ item.email }}</p>
                </div>
                <div class="div-col">
                    <p class="text-admin"><strong>был:</strong></p>
                    <p class="text-admin">{{ item.last_login }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_create.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content-container %}
    <div class="content-container">
    <h2 class="registration_title__myadmin">Панель администратора</h2>
        {% include 'adminapp/includes/inc__myadmin-menu.html' %}
        <div class="form_wrapper">
            <div class="login_form">
                <h1 class="regisration_title">{{ page_title | title }}</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="Сохранить">
                </form>
            </div>
            <a href="{% url 'myadmin:productcategory_products' request.resolver_match.kwargs.pk %}"
               class="btn btn-secondary">
                    К списку товаров
                </a>
{#            <a href="{% url 'myadmin:productcategory_products' object.category.pk %}" class="btn-admin-3">#}
{#                    К списку товаров#}
{#                </a>#}
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content-container %}
    <div class="content-container">

        <h2 class="myadmin-title">Панель администратора</h2>
        {% include 'adminapp/includes/inc__myadmin-menu.html' %}

            <h1 class="regisration_title_myadmin">{{ productcategory.name }}</h1>
<table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">id</th>
                <th scope="col">Название товара</th>
                <th scope="col">Инструменты</th>
                <th scope="col">Описание</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                    <th scope="row"></th>
                    <td></td>
                    <td>
                        <a href="{% url 'myadmin:product_create' productcategory.pk %}"
                           class="btn btn-dark">Новый продукт</a>
                        </td>
                    <td>
                    </td>
                <td></td>
                <td></td>
                <td></td>
                </tr>
            {% for item in object_list %}
                <tr class="{% if not item.is_active %}not_active{% endif %}">
                    <th scope="row">{{ item.id }}</th>
                    <td class="description_myadmin_product">{{ item.name }}</td>

                    <td class="myadmin_btn_product">
                        <a href="{% url 'myadmin:product_read' item.pk %}"
                           class="btn btn-secondary">Подробнее</a>
 <a href="{% url 'myadmin:product_update' item.pk %}"
                           class="btn btn-success">Редактировать</a><br>
                  <a href="{% url 'myadmin:product_delete' item.pk %}" class="btn btn-danger">Удалить</a>
                    </td>
                    <td>{{ item.description }}

                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>







{#        <div class="user_list_wrapper">#}
{##}
{#            <div class="user_list first-row">#}
{#                <div class="div-col-product-list"></div>#}
{#                <div class="div-col-product-list">#}
{#                    <a href="{% url 'myadmin:product_create' productcategory.pk %}" class="btn-admin-2">Новый продукт</a>#}
{#                </div>#}
{#                <div class="div-col">#}
{#                </div>#}
{##}
{#            </div>#}
{#            {% for object in object_list %}#}
{##}
{#                <div class="user_list {% if not object.is_active %}not_active{% endif %}">#}
{##}
{#                    <div class="div-col-product-list">#}
{#                        <p class="text-admin">{{ object.name }}</p>#}
{#                    </div>#}
{#                    <div class="div-col-product-list">#}
{#                        <p class="text-admin"></p>#}
{#                        <a href="{% url 'myadmin:product_read' object.pk %}"#}
{#                           class="btn-admin-1">Подробнее</a>#}
{#                        <a href="{% url 'myadmin:product_update' object.pk %}"#}
{#                           class="btn-admin-2">Редактировать</a>#}
{#                        <a href="{% url 'myadmin:product_delete' object.pk %}" class="btn-admin-2">Удалить</a>#}
{#                    </div>#}
{#                    <div class="div-col">#}
{#                        <p class="text-admin">{{ object.description }}</p>#}
{#                    </div>#}
{##}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}

    </div>
{% endblock %}

adminapp/templates/adminapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content-container %}
    <div class="content-container">
        <h2 class="myadmin-title">Панель администратора</h2>
        {% include 'adminapp/includes/inc__myadmin-menu.html' %}

    <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название категории</th>
                <th scope="col">Инструменты</th>
                <th scope="col">Описание</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                    <th scope="row"></th>
                    <td></td>
                    <td>
                        <a href="{% url 'myadmin:productcategory_create' %}" class="btn btn-dark">Новая категория</a>
                        </td>
                    <td>
                    </td>
                <td></td>
                <td></td>
                <td></td>
                </tr>
            {% for item in object_list %}
                <tr class="{% if not item.is_active %}not_active{% endif %}">
                    <th scope="row">{{ item.id }}</th>
                    <td>{{ item.name }}</td>
                    <td><a href="{% url 'myadmin:productcategory_products' item.pk %}"#}
                           class="btn btn-primary">Товары категории</a><br>
 <a href="{% url 'myadmin:productcategory_update' item.pk %}"
                           class="btn btn-success">Редактировать</a><br>
                  <a href="{% url 'myadmin:productcategory_delete' item.pk %}" class="btn btn-danger">Удалить</a>
                    </td>
                    <td>{{ item.description }}

                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>






{#        <div class="user_list_wrapper">#}
{#            <div class="user_list first-row">#}
{#                <div class="div-col"></div>#}
{#                <div class="div-col">#}
{#                    <a href="{% url 'myadmin:productcategory_create' %}" class="btn-admin-2">Новая категория</a>#}
{#                </div>#}
{#                <div class="div-col">#}
{#                </div>#}
{#                <div class="div-col"></div>#}
{#                <div class="div-col"></div>#}
{#                <div class="div-col"></div>#}
{#            </div>#}
{#            {% for object in object_list %}#}
{#                <div class="user_list {% if not object.is_active %}not_active{% endif %}">#}
{#                    <div class="div-col">#}
{#                        <p class="text-admin">{{ object.name }}</p>#}
{#                    </div>#}
{#                    <div class="div-col">#}
{#                        <p class="text-admin"></p>#}
{#                        <a href="{% url 'myadmin:productcategory_products' object.pk %}"#}
{#                           class="btn-admin-1">Товары категории</a>#}
{#                        <a href="{% url 'myadmin:productcategory_update' object.pk %}"#}
{#                           class="btn-admin-1">Редактировать</a>#}
{#                        <a href="{% url 'myadmin:productcategory_delete' object.pk %}" class="btn-admin-2">Удалить</a>#}
{#                    </div>#}
{#                    <div class="div-col">#}
{#                        <p class="text-admin">{{ object.description }}</p>#}
{#                    </div>#}
{#                    <div class="div-col">#}
{#                    </div>#}
{#                    <div class="div-col">#}
{##}
{#                    </div>#}
{#                    <div class="div-col">#}
{##}
{#                    </div>#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}
    </div>
{% endblock %}