authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path, re_path
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.index, name='index'),
    re_path(r'^add/(?P<slug>[-\w]+)/', basketapp.basket_add, name='add'),
    re_path(r'^delete/(?P<pk>\d+)/', basketapp.basket_delete, name='delete'),
    re_path(r'^update/(?P<pk>\d+)/(?P<quantity>\d+)/', basketapp.basket_update, name='update'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

import mainapp.views as mainapp

urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^myadmin/', include('adminapp.urls', namespace='myadmin')),
    re_path(r'^callback/', include('callbackapp.urls', namespace='callback')),
    re_path(r'^news/', include('newsapp.urls', namespace='news')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    re_path(r'^', include('social_django.urls', namespace='social')),
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
# import mainapp.views as mainapp
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', mainapp.index, name='index'),

    re_path(r'^shop/$', mainapp.shop, name='shop'),
    re_path(r'^shop/page/(?P<page>\d+)/$', mainapp.shop, name='shop_paginator'),

    re_path(r'^product/(?P<slug>[-\w]+)/$', mainapp.product, name='product'),

    re_path(r'^category/(?P<slug>[-\w]+)/$', mainapp.category, name='category'),
    re_path(r'^category/(?P<slug>[-\w]+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    re_path(r'^search/$', mainapp.search, name='search'),
    # re_path(r'^search/$', mainapp.SearchView.as_view(), name='search'),

]

newsapp/urls.py
from django.urls import path, re_path
# import mainapp.views as mainapp
from newsapp import views as newsapp

app_name = 'newsapp'

urlpatterns = [
    re_path(r'^$', newsapp.index, name='index'),
    re_path(r'^(?P<slug>[-\w]+)/$', newsapp.news, name='new'),

    # re_path(r'^shop/$', mainapp.shop, name='shop'),
    # re_path(r'^shop/page/(?P<page>\d+)/$', mainapp.shop, name='shop_paginator'),
    #
    # re_path(r'^product/(?P<slug>[-\w]+)/$', mainapp.product, name='product'),
    #
    # re_path(r'^category/(?P<slug>[-\w]+)/$', mainapp.category, name='category'),
    # re_path(r'^category/(?P<slug>[-\w]+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    # re_path(r'^search/$', mainapp.search, name='search'),
    # # re_path(r'^search/$', mainapp.SearchView.as_view(), name='search'),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Имя категории', max_length=128, unique=True)
    slug = models.SlugField(verbose_name='Слаг', max_length=128, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='Активность', default=True)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'


# class ProductSubCategory(models.Model):
#     category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
#     name = models.CharField(verbose_name='Имя подкатегории', max_length=128, unique=True)
#     description = models.TextField(verbose_name='Описание подкатегории', blank=True)
#
#     def __str__(self):
#         return f"{self.name}"
#
#     class Meta:
#         verbose_name = 'Подкатегория товара'
#         verbose_name_plural = 'Подкатегории товаров'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    # subcategory = models.ForeignKey(ProductSubCategory, on_delete=models.CASCADE, default=None)
    name = models.CharField(verbose_name='Название товара', max_length=128, unique=True)
    slug = models.SlugField(verbose_name='слаг', max_length=128, unique=True)
    image = models.ImageField(upload_to='product_images', default='users_avatars/default.jpg')
    short_desc = models.TextField(verbose_name='Краткое описание товара', blank=True)
    description = models.TextField(verbose_name='Полное описание товара', blank=True)
    price = models.DecimalField(verbose_name='Цена товара', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='На складе', default=0)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    is_active = models.BooleanField(verbose_name='Активность', default=True)
    to_order = models.BooleanField(verbose_name='Под заказ', default=False)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

mainapp/views.py
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from newsapp.models import News
from .models import *
from django.shortcuts import render_to_response


def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        founded_products = Product.objects.filter(
            Q(name__icontains=q) | Q(description__icontains=q) | Q(short_desc__icontains=q)
        ).order_by('name')
        # founded_products = Product.objects.filter(
        #     Q(name__in=q) | Q(description__in=q) | Q(short_desc__in=q)
        # ).order_by('name')
        context = {
            'page_title': 'Результаты поиска',
            'founded_products': founded_products,
            'query': q,
        }
        return render_to_response('mainapp/search.html', context)
    else:
        context = {
            'page_title': 'Результаты поиска',
        }
        return render_to_response('mainapp/search.html', context)


# def search_form(request):
#     return render_to_response('mainapp/search.html')


# class SearchView(View):
#     template_name = "mainapp/search.html"
#
#     def get_result_search(self, request, *args, **kwargs):
#         query = self.request.GET.get('q')
#         founded_products = Product.objects.filter(Q(name__icontains=query))
#         context = {
#             'founded_products': founded_products,
#             'query': query,
#         }
#         return render(self.request, self.template_name, context)


# def get_products_menu():
#     return ProductCategory.objects.all().exclude(is_active=False)

# def bad_search(request):
#     # The following line will raise KeyError if 'q' hasn't
#     # been submitted!
#     message = 'You searched for: %r' % request.GET['q']
#     return HttpResponse(message)


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')
    else:
        []


def index(request):
    all_products = Product.objects.all().order_by('?')[:6]
    all_news = News.objects.all().order_by('-created')[:4]
    context = {
        'page_title': 'РФснаб.ру - комплексное снабжение',
        'all_products': all_products,
        'all_news': all_news,
        # 'basket': get_basket(request),
    }
    return render(request, 'mainapp/index.html', context)


def shop(request, slug=None, page=1):
    all_products = Product.objects.all()
    paginator = Paginator(all_products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    context = {
        'page_title': 'каталог',
        'all_products': products_paginator,
    }
    return render(request, 'mainapp/shop.html', context)


def category(request, slug, page=1):
    all_products = Product.objects.filter(category__slug=slug).exclude(is_active=False)
    single_category = ProductCategory.objects.filter(slug=slug)
    paginator = Paginator(all_products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    context = {
        'all_products': products_paginator,
        'single_category': single_category,
    }
    return render(request, "mainapp/category.html", context)


def product(request, slug):
    single_product = Product.objects.filter(slug=slug)
    same_products = Product.objects.all().filter(category__product__slug=slug).exclude(slug=slug).order_by('?')[:4]
    context = {
        'single_product': single_product,
        'same_products': same_products,
    }
    return render(request, "mainapp/product.html", context)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% block title %}
        <title>{{ page_title | capfirst }}</title>
    {% endblock %}
    {% block css %}

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {#        <link href="img/burning-ico.png" rel="shortcut icon" type="image/x-icon">#}
        <link href="{% static 'img/burning-ico.png' %}" rel="shortcut icon" type="image/x-icon">
        {#        <link href="{% static 'images/webclip.png' %}" rel="apple-touch-icon">#}
    {% endblock %}

</head>
<body>
{#<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="label" aria-hidden="true">#}
<div class="modal" id="modal" tabindex="-1" role="dialog" aria-labelledby="label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <div></div>
                <h5 class="modal-title" id="label">Обратный звонок</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'callback:index' %}" method="post" enctype="multipart/form-data">
                    {% include "callbackapp/modal_window.html" %}
                </form>
            </div>
            <div class="modal-footer">
{#                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>#}
                <button type="button" class="btn btn-primary" id="add-button">Добавить</button>
            </div>
        </div>
    </div>
</div>


<div class="site-wrapper">
    <div class="top">
        <div class="header">
            <div class="header-wrapper">
                <div class="header-upper-section">
                    <a href="{% url 'main:index' %}" class="logo-upper-section">
                    </a>

                    <form action="{% url 'main:search' %}" method="GET" class="search-upper-form-section">
                        <input type="text" placeholder="Поиск по каталогу" name="q"
                               class="input-search-upper-section">
                        <button type="submit" class="search-upper-section-btn"></button>
                    </form>
                    <div class="text-wrapper-upper-section">
                        <p class="text-upper-section">ООО «МСВ», г. Сыктывкар, ул. Гаражная, д. 9, офис 105</p>
                        <a href="#" class="header-phone">+7(8212)29-69-71</a>
                        <div class="callback-box">
                            <a href="#" class="header-phone-left">8-800-511-80-60</a>
                            <a href="#" class="callback-link js-button-campaign" data-toggle="modal"
                               data-target="#modal">обратный звонок</a>

                        </div>
                        <p class="footer-text"> Сегодня {% now "DATE_FORMAT" %}</p>
                    </div>
                </div>

                {% include 'mainapp/includes/inc__menu_wrapper.html' %}
            </div>
        </div>




        {% block content-container %}
        {% endblock %}
    </div>
    <div class="footer">
        <div class="footer-wrapper">
            <div class="footer-box">
                <div class="footer-col">
                    <img src="{% static 'img/visa_logos.png' %}" alt="VISA, MASTERCARD">
                    <p class="footer-text">ИНН 1101059443</p>
                    <p class="footer-text">ОГРН 1161101055620</p>
                </div>
                <div class="footer-col">
                    <p class="fotter-title">Меню</p>
                    <ul class="menu-footer">
                        <li><a href="#" class="footer-menu-link">Главная</a></li>
                        <li><a href="#" class="footer-menu-link">О компании</a></li>
                        <li><a href="#" class="footer-menu-link">Доставка</a></li>
                        <li><a href="#" class="footer-menu-link">Новости</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <p class="fotter-title">Услуги</p>
                    <ul class="menu-footer">
                        <li><a href="#" class="footer-menu-link">Каталог всех товаров</a></li>
                        <li><a href="#" class="footer-menu-link">Противопожарное оборудование</a></li>
                        <li><a href="#" class="footer-menu-link">Продукция торговой малки Шанс</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <p class="fotter-title">Контакты</p>
                    <p class="footer-text"><a href="tel:+78212296971" class="footer-phone">+7(8212)29-69-71</a></p>
                    <p class="footer-text">Режим работы: пн-пт с 9.00 до 18.00, обед с 13.00 до 14.00</p>
                    <ul class="menu-footer">
                        <li><a href="#" class="footer-menu-link">Политика конфиденциальности</a></li>
                    </ul>
                </div>
            </div>
            <p class="copyright-text">&copy; 2019, ООО «МСВ»</p>
        </div>
    </div>
</div>
{% block js %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
{#    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"#}
{#            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"#}
{#            crossorigin="anonymous"></script>#}
{#    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>






    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <script src="{% static 'js/basket_scripts.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/orders_scripts.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>

{% endblock %}

</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content-container %}

    <div class="content-container_on_main">
        {% include 'mainapp/includes/inc__wrapper_add_cart.html' %}
        <div class="slide-container">
            <a href="#" class="slider-left-arrow">
                <img src="{% static 'img/left-arrow.png' %}" alt="left arrow">
            </a>
            <div class="slider-content-box">
                <div class="slider-pagination-box">
                    <a href="#" class="slider-circle"></a>
                    <a href="#" class="slider-circle circle-active"></a>
                    <a href="#" class="slider-circle"></a>
                </div>
            </div>
            <a href="#" class="slider-right-arrow">
                <img src="{% static 'img/right-arrow.png' %}" alt="right arrow">
            </a>
        </div>
        <h2 class="text-title">Наши акции и скидки</h2>

        <div class="search-from-wrapper-on-main">
            <form action="#" class="search-form-on-main-container">
                <input type="text" placeholder="Поиск по каталогу" class="input-search-from-wrapper-on-main">
                <button type="submit" class="btn-search-from-wrapper-on-main">Найти</button>
                <div class="slider-box">
                    <div class="price-slider">
                        <div class="ui-slider-range"></div>
                        <div class="ui-slider-handle"></div>
                    </div>
                </div>
                <input type="text" placeholder="0" class="input-search-from-wrapper-on-main-left">
                <input type="text" placeholder="15000" class="input-search-from-wrapper-on-main-right">
            </form>
        </div>
        <div class="card-container">
            {% if all_products %}
                {% for item in all_products %}
                    <a href="{% url 'main:product' item.slug %}" class="category-product-card-box">
                        <h3 class="title-product-card">{{ item.name }}</h3>
                        {% if not item.to_order %}
                            <p class="text-in-stock">в наличии</p>
                        {% else %}
                            <p class="text-out-stock">под заказ</p>
                        {% endif %}
                        {#                        style="background-image: url(/media/{{ item.image }});"#}
                        <div style="background-image: url(/media/{{ item.image }}); background-position: 50%;
                                background-size: contain; background-repeat: no-repeat"
                             class="product-card-image-box">
                            {#                            <img src="/media/{{ item.image }}" alt="" class="img_product_card_image">#}
                        </div>
                        <p class="price-card-text">{{ item.price }} руб.</p>
                        <div class="cart-wrapper">
                            {% if item.to_order %}
                                <div class="cart-out-stock"></div>
                            {% else %}
                                <div class="cart-in-stock"></div>
                            {% endif %}
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <div style="margin: 50px auto;">
                    <p style="font-size: 32px;">В данный момент товара нет</p>
                </div>
            {% endif %}

        </div>
        <div class="button-to-cataloge-wrapper">
            <a href="{% url 'main:shop' %}" class="button-to-cataloge">смотреть все</a></div>
        <h2 class="text-title">Как мы работаем</h2>
        <div class="as-we-work-box">
            <div class="as-we-work-card">
                <div class="as-we-work-image"></div>
                <div class="as-we-work-number">1</div>
                <p class="as-we-work-description">Вы определяетесь с необходимым оборудованием</p>
            </div>
            <div class="as-we-work-card">
                <div class="as-we-work-image-1"></div>
                <div class="as-we-work-number">2</div>
                <p class="as-we-work-description">Оформляете заявку по телефону или по e-mail</p>
            </div>
            <div class="as-we-work-card">
                <div class="as-we-work-image-2"></div>
                <div class="as-we-work-number">3</div>
                <p class="as-we-work-description">Обмениваемся документами для заключения договора</p>
            </div>
            <div class="as-we-work-card">
                <div class="as-we-work-image-3"></div>
                <div class="as-we-work-number">4</div>
                <p class="as-we-work-description">Вы оплачиваете счет за оборудование</p>
            </div>
            <div class="as-we-work-card">
                <div class="as-we-work-image-4"></div>
                <div class="as-we-work-number">5</div>
                <p class="as-we-work-description">Забираете товар в офисе или получаете доставку</p>
            </div>
            <div class="as-we-work-card">
                <div class="as-we-work-image-5"></div>
                <div class="as-we-work-number">6</div>
                <p class="as-we-work-description">Продолжаем взаимовыгодное сотрудничество</p>
            </div>
        </div>
        <h2 class="text-title">Почему выбирают нас</h2>
        <div class="why-choose-us-box">
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Широкий ассортимент оборудования</p>
            </div>
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Приемлемые цены на весь каталог товаров</p>
            </div>
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Гибкая система скидок постоянным клиентам</p>
            </div>
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Самые короткие сроки поставки клиентам</p>
            </div>
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Доставка товара по всей России</p>
            </div>
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Консультация и помощь с выбором</p>
            </div>
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Гарантия качества на все оборудование</p>
            </div>
            <div class="why-choose-us-card">
                <img src="{% static 'img/check_img.png' %}" alt="image" class="why-choose-us-card-image">
                <p class="why-choose-us-card-text">Качественное техническое обслуживание</p>
            </div>
        </div>
        <h2 class="text-title">Новости компании</h2>
        <div class="news-company-box">
            {% if all_news %}
                {% for item in all_news %}
                <a href="{% url 'news:new' item.slug %}" class="news-company-card">
                    <p class="title-news-company-box">{{ item.title }}</p>
                    <div class="system-information-news-card">
                        <p class="post-date">{{ item.created | date:"SHORT_DATE_FORMAT" }}</p>
                        <p class="author-post">{{ item.author }}</p>
                    </div>
                    <div style="background-image: url(/media/{{ item.image }}); background-position: 50%;
                                           background-size: contain; background-repeat: no-repeat"
                         class="news-company-card-image"></div>
                </a>
                {% endfor %}
            {% else %}
                <h2 class="news_title">На данный момент нет ни одной новости</h2>
            {% endif %}
            {#            <a href="#" class="news-company-card">#}
            {#                <p class="title-news-company-box">Тестовая новость 1</p>#}
            {#                <div class="system-information-news-card">#}
            {#                    <p class="post-date">05.06.2019</p>#}
            {#                    <p class="author-post">admin</p>#}
            {#                </div>#}
            {#                <div class="news-company-card-image"></div>#}
            {#            </a>#}
            {#            <a href="#" class="news-company-card">#}
            {#                <p class="title-news-company-box">Тестовая новость 1</p>#}
            {#                <div class="system-information-news-card">#}
            {#                    <p class="post-date">05.06.2019</p>#}
            {#                    <p class="author-post">admin</p>#}
            {#                </div>#}
            {#                <div class="news-company-card-image"></div>#}
            {#            </a>#}
            {#            <a href="#" class="news-company-card">#}
            {#                <p class="title-news-company-box">Тестовая новость 1</p>#}
            {#                <div class="system-information-news-card">#}
            {#                    <p class="post-date">05.06.2019</p>#}
            {#                    <p class="author-post">admin</p>#}
            {#                </div>#}
            {#                <div class="news-company-card-image"></div>#}
            {#            </a>#}
        </div>

    </div>
{% endblock %}

mainapp/templates/mainapp/search.html
{% extends 'mainapp/base.html' %} }
{% load static %}

{% block content-container %}
    <div class="content-container_on_main">
    <h2 class="search-title">Результаты запроса для: <strong>{{ query }}</strong></h2>
    {% if founded_products %}
        <h3 class="result_title">Найдено: {{ founded_products|length }}</h3>
        {% for item in founded_products %}
             <p class="search_link_p"><a href="{% url 'main:product' item.slug %}" class="search_link">
                {{ item.name }}</a></p>
        {% endfor %}
          {% else %}
         <h3 class="result_title">Результаты поиска: Ничего не найдено</h3>

    {% endif %}
    </div>
{% endblock %}